### ISSUE TITLE
Can't deploy to Rinkeby or Run Test for test_can_pick_winner

### ISSUE THREAD

**Issue by Harsh-Gill** [PatrickAlphaC/smartcontract-lottery#51]
I thought as first it is because vrf_coordinator adress, keyhash and the fee have changed. So i made the following changes.
```
  rinkeby:
    vrf_coordinator: "0x6168499c0cFfCaCD319c818142124B7A15E857ab"
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    keyhash: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
    fee: 300000000000000000
    verfiy: True
```

But i still keep on getting this vague error when running the test :
brownie test -k test_can_pick_winner --network rinkeby -s

tests/test_lottery_integration.py::test_can_pick_winner RUNNING
Deployed lottery!
Fund contract!
tests/test_lottery_integration.py::test_can_pick_winner FAILED
tests/test_lottery_unit.py::test_can_pick_winner_correctly SKIPPED

======================================== FAILURES ========================================
__________________________________ test_can_pick_winner __________________________________

    def test_can_pick_winner():
        if network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
            pytest.skip()
        lottery = deploy_lottery()
        account = get_account()
        lottery.startLottery({"from": account})
        lottery.enter({"from": account, "value": lottery.getEntranceFee()})
        lottery.enter({"from": account, "value": lottery.getEntranceFee()})
        fund_with_link(lottery)
>       lottery.endLottery({"from": account})
E       ValueError: Gas estimation failed: 'execution reverted'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.

tests/test_lottery_integration.py:21: ValueError

Any help would be very appreciated, thanks!
